const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    version: '1.0.0',
    title: 'DQM Backend API',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:5000',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'DQM Front End Endpoints',
      description:
        'These endpoints are used to interact with Google cloud services such as Google Cloud Job Scheduler, BigQuery, Workflow and Cloud Storage Bucket',
    },
  ],
};

const outputFile = 'build/swagger.json';
const endpointsFiles = ['src/app.ts'];

swaggerAutogen(outputFile, endpointsFiles, doc);
