"""
Copyright 2022 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import unittest

from rules.text import is_phone_number

# generated by Faker package
# yapf: disable
random_phone_numbers = [
    "(969)788-2691",
    "077.385.0589",
    "001-473-547-1259",
    "(338)932-9400",
    "532-494-2814",
    "3867258917",
    "001-657-652-5947",
    "001-966-228-1334",
    "(000)565-8440",
    "350.203.1877",
    "489-585-5155",
    "001-897-544-6160",
    "492.053.0657",
    "+1-093-414-0852",
    "(062)431-0396",
    "3206956507",
    "+1-319-176-6308",
    "001-785-701-7657",
    "001-606-151-5396",
    "667-372-7022",
    "(311)705-9078",
    "001-107-910-4033",
    "180-238-5347",
    "844-612-3576",
    "+1-985-018-8966",
    "001-619-028-5335",
    "001-869-794-8946",
    "+1-269-452-9969",
    "1729278909",
    "596-481-1259",
    "(709)726-1405",
    "108-091-4499",
    "2081586070",
    "001-799-506-6901",
    "+1-095-628-1595",
    "(608)956-7813",
    "932.106.1365",
    "(207)400-4390",
    "(624)385-1431",
    "983-727-1681",
    "(038)892-4674",
    "319.312.7995",
    "5311251811",
    "001-284-642-0664",
    "241-071-7175",
    "123-547-3740",
    "(900)701-1886",
    "001-312-960-7414",
    "8296708979",
    "450.021.6129",
    "073-160-3142",
    "414-082-8355",
    "+1-234-041-7823",
    "(584)275-2078",
    "001-433-860-9817",
    "001-589-979-8404",
    "001-777-488-8687",
    "482.621.8158",
    "+1-295-839-8763",
    "014-115-3846",
    "001-979-620-6328",
    "(442)488-9123",
    "(354)481-5773",
    "001-445-524-5188",
    "001-545-925-7050",
    "2223477383",
    "913.665.0782",
    "(483)013-4569",
    "986-971-5295",
    "886-624-7226",
    "+1-405-606-3362",
    "507.446.8376",
    "001-624-510-0868",
    "+1-076-710-8226",
    "682-784-5766",
    "(794)131-8732",
    "001-238-615-7520",
    "231-993-0332",
    "(512)180-3204",
    "787.273.9105",
    "001-607-066-6051",
    "001-957-020-9292",
    "001-948-359-0968",
    "929.232.6003",
    "+1-395-568-6503",
    "(331)820-2828",
    "937-352-7986",
    "+1-190-266-7467",
    "928.281.6386",
    "596.401.9601",
    "527-168-6416",
    "001-344-644-0222",
    "+1-072-988-3257",
    "212.092.7361",
    "632-247-6152",
    "+31634254732",
    "010-962-6127",
    "+1-095-064-8942",
    "724.843.7749",
    "7586689617",
    "0682538431",
]
# yapf: enable


class IsPhoneNumber(unittest.TestCase):

    def setUp(self) -> None:
        self.rule_checker = is_phone_number()
        return super().setUp()

    def test_returns_callable(self):
        self.assertTrue(callable(self.rule_checker))

    def test_phone_numbers(self):
        # standard phone number
        for number in random_phone_numbers:
            self.assertIsNotNone(self.rule_checker(number))

    def test_non_phone_numbers(self):
        # standard phone number
        self.assertIsNone(self.rule_checker('test'))
        self.assertIsNone(self.rule_checker('23598734928057034978'))
        self.assertIsNone(self.rule_checker('00000000000'))
        self.assertIsNone(self.rule_checker('test'))
        self.assertIsNone(self.rule_checker('test'))
