project_id            = "tentacles-test-363712"
cloud_storage_region  = "EU"
workflow_region       = "europe-west1"
cloud_function_region = "europe-west1"
service_account_name  = "dqm-account"
config_bucket         = "dqm_config"
